### PR TITLE
Allow maximum chunk length to be set.

### PR DESCRIPTION
**Pull request by Apostrophii**
Implements https://github.com/google/budou/issues/39

### CODE REVIEW

**Comment by Apostrophii** [comment]
Signed : )

**Comment by Apostrophii** [comment]
Hm... I think that should be fixed now

**Comment by tushuhei** [comment]
Hi Apostrophii,
Thank you for working on this! I really appreciate it.
Actually, the intention in #39 was more like giving up making a chunk if the word is too long rather than making a chunk up to the maximum length.

For example, a sentence "これがマルチスクリーンです。" can be rendered like
```
これが
マルチスクリーン
です。
```
but it may look ugly because the length of chunks varies a lot (3, 8, 3).

So, I thought it would be more legible if the long chunk ("マルチスクリーン", in this case) is split like:
```
これがマルチス
クリーンです。
```

This should be accomplished by not setting "マルチスクリーン" as `inline-block`. In other words, HTML output looks like: `<span class="budou">これが</span>マルチスクリーン<span class="budou">です。</span>` where `<style>.budou {display: inline-block;}</style>`.

The interface looks good, so I appreciate if you could make those fixes accordingly.

**Comment by Apostrophii** [comment]
Ahh, I see now. No problem then, I'll make those changes.

**Comment by Apostrophii** [comment]
These changes have been implemented by https://github.com/google/budou/pull/70.

**Pull request closed without merging**
